# Generated by Django 4.0 on 2022-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(max_length=32, verbose_name='上次登入'),
        ),
    ]
